version: '3'

services:
  user-service:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app/app
    environment:
      # Use DATABASE_URL for DB connection (preferred)
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hotlabel_users
      # Deprecated: POSTGRES_* variables are no longer used by the app, but kept for backward compatibility
      # - POSTGRES_SERVER=db
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB=hotlabel_users
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotlabel_users
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
