"""Initial migration

Revision ID: 1fc34c5c2173
Revises: 
Create Date: 2025-06-09 14:01:09.708497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc34c5c2173'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expertise_areas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['expertise_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expertise_areas_id'), 'expertise_areas', ['id'], unique=False)
    op.create_index(op.f('ix_expertise_areas_name'), 'expertise_areas', ['name'], unique=False)
    op.create_index(op.f('ix_expertise_areas_slug'), 'expertise_areas', ['slug'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email_hash', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('additional_languages', sa.JSON(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('expertise_level', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('profile_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_email_hash'), 'user_profiles', ['email_hash'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('profile_expertise',
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('expertise_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['expertise_id'], ['expertise_areas.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], )
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publisher_id', sa.String(), nullable=False),
    sa.Column('browser_fingerprint', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('analytics_opt_in', sa.Boolean(), nullable=True),
    sa.Column('personalization_opt_in', sa.Boolean(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_attempted', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_browser_fingerprint'), 'user_sessions', ['browser_fingerprint'], unique=False)
    op.create_index(op.f('ix_user_sessions_country'), 'user_sessions', ['country'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_language'), 'user_sessions', ['language'], unique=False)
    op.create_index(op.f('ix_user_sessions_publisher_id'), 'user_sessions', ['publisher_id'], unique=False)
    op.create_table('user_statistics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=True),
    sa.Column('total_tasks_attempted', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_task_time_ms', sa.Integer(), nullable=True),
    sa.Column('fastest_task_time_ms', sa.Integer(), nullable=True),
    sa.Column('slowest_task_time_ms', sa.Integer(), nullable=True),
    sa.Column('task_type_distribution', sa.JSON(), nullable=True),
    sa.Column('average_quality_score', sa.Float(), nullable=True),
    sa.Column('quality_distribution', sa.JSON(), nullable=True),
    sa.Column('expertise_level', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('first_task_date', sa.DateTime(), nullable=True),
    sa.Column('last_task_date', sa.DateTime(), nullable=True),
    sa.Column('active_days', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_statistics_id'), 'user_statistics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_statistics_id'), table_name='user_statistics')
    op.drop_table('user_statistics')
    op.drop_index(op.f('ix_user_sessions_publisher_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_language'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_country'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_browser_fingerprint'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('profile_expertise')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email_hash'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_expertise_areas_slug'), table_name='expertise_areas')
    op.drop_index(op.f('ix_expertise_areas_name'), table_name='expertise_areas')
    op.drop_index(op.f('ix_expertise_areas_id'), table_name='expertise_areas')
    op.drop_table('expertise_areas')
    # ### end Alembic commands ###
